# countries.py

COUNTRIES = [
    {"name": "Afghanistan", "flag_url": "https://flagcdn.com/w320/af.png", "continent": "Asia"},
    {"name": "Albania", "flag_url": "https://flagcdn.com/w320/al.png", "continent": "Europe"},
    {"name": "Algeria", "flag_url": "https://flagcdn.com/w320/dz.png", "continent": "Africa"},
    {"name": "Andorra", "flag_url": "https://flagcdn.com/w320/ad.png", "continent": "Europe"},
    {"name": "Angola", "flag_url": "https://flagcdn.com/w320/ao.png", "continent": "Africa"},
    {"name": "Antigua and Barbuda", "flag_url": "https://flagcdn.com/w320/ag.png", "continent": "North America"},
    {"name": "Argentina", "flag_url": "https://flagcdn.com/w320/ar.png", "continent": "South America"},
    {"name": "Armenia", "flag_url": "https://flagcdn.com/w320/am.png", "continent": "Asia"},
    {"name": "Australia", "flag_url": "https://flagcdn.com/w320/au.png", "continent": "Oceania"},
    {"name": "Austria", "flag_url": "https://flagcdn.com/w320/at.png", "continent": "Europe"},
    {"name": "Azerbaijan", "flag_url": "https://flagcdn.com/w320/az.png", "continent": "Asia"},
    {"name": "Bahamas", "flag_url": "https://flagcdn.com/w320/bs.png", "continent": "North America"},
    {"name": "Bahrain", "flag_url": "https://flagcdn.com/w320/bh.png", "continent": "Asia"},
    {"name": "Bangladesh", "flag_url": "https://flagcdn.com/w320/bd.png", "continent": "Asia"},
    {"name": "Barbados", "flag_url": "https://flagcdn.com/w320/bb.png", "continent": "North America"},
    {"name": "Belarus", "flag_url": "https://flagcdn.com/w320/by.png", "continent": "Europe"},
    {"name": "Belgium", "flag_url": "https://flagcdn.com/w320/be.png", "continent": "Europe"},
    {"name": "Belize", "flag_url": "https://flagcdn.com/w320/bz.png", "continent": "North America"},
    {"name": "Benin", "flag_url": "https://flagcdn.com/w320/bj.png", "continent": "Africa"},
    {"name": "Bhutan", "flag_url": "https://flagcdn.com/w320/bt.png", "continent": "Asia"},
    {"name": "Bolivia", "flag_url": "https://flagcdn.com/w320/bo.png", "continent": "South America"},
    {"name": "Bosnia and Herzegovina", "flag_url": "https://flagcdn.com/w320/ba.png", "continent": "Europe"},
    {"name": "Botswana", "flag_url": "https://flagcdn.com/w320/bw.png", "continent": "Africa"},
    {"name": "Brazil", "flag_url": "https://flagcdn.com/w320/br.png", "continent": "South America"},
    {"name": "Brunei", "flag_url": "https://flagcdn.com/w320/bn.png", "continent": "Asia"},
    {"name": "Bulgaria", "flag_url": "https://flagcdn.com/w320/bg.png", "continent": "Europe"},
    {"name": "Burkina Faso", "flag_url": "https://flagcdn.com/w320/bf.png", "continent": "Africa"},
    {"name": "Burundi", "flag_url": "https://flagcdn.com/w320/bi.png", "continent": "Africa"},
    {"name": "Cabo Verde", "flag_url": "https://flagcdn.com/w320/cv.png", "continent": "Africa"},
    {"name": "Cambodia", "flag_url": "https://flagcdn.com/w320/kh.png", "continent": "Asia"},
    {"name": "Cameroon", "flag_url": "https://flagcdn.com/w320/cm.png", "continent": "Africa"},
    {"name": "Canada", "flag_url": "https://flagcdn.com/w320/ca.png", "continent": "North America"},
    {"name": "Central African Republic", "flag_url": "https://flagcdn.com/w320/cf.png", "continent": "Africa"},
    {"name": "Chad", "flag_url": "https://flagcdn.com/w320/td.png", "continent": "Africa"},
    {"name": "Chile", "flag_url": "https://flagcdn.com/w320/cl.png", "continent": "South America"},
    {"name": "China", "flag_url": "https://flagcdn.com/w320/cn.png", "continent": "Asia"},
    {"name": "Colombia", "flag_url": "https://flagcdn.com/w320/co.png", "continent": "South America"},
    {"name": "Comoros", "flag_url": "https://flagcdn.com/w320/km.png", "continent": "Africa"},
    {"name": "Congo (Brazzaville)", "flag_url": "https://flagcdn.com/w320/cg.png", "continent": "Africa"},
    {"name": "Congo (Kinshasa)", "flag_url": "https://flagcdn.com/w320/cd.png", "continent": "Africa"},
    {"name": "Costa Rica", "flag_url": "https://flagcdn.com/w320/cr.png", "continent": "North America"},
    {"name": "Croatia", "flag_url": "https://flagcdn.com/w320/hr.png", "continent": "Europe"},
    {"name": "Cuba", "flag_url": "https://flagcdn.com/w320/cu.png", "continent": "North America"},
    {"name": "Cyprus", "flag_url": "https://flagcdn.com/w320/cy.png", "continent": "Asia"},
    {"name": "Czechia", "flag_url": "https://flagcdn.com/w320/cz.png", "continent": "Europe"},
    {"name": "Denmark", "flag_url": "https://flagcdn.com/w320/dk.png", "continent": "Europe"},
    {"name": "Djibouti", "flag_url": "https://flagcdn.com/w320/dj.png", "continent": "Africa"},
    {"name": "Dominica", "flag_url": "https://flagcdn.com/w320/dm.png", "continent": "North America"},
    {"name": "Dominican Republic", "flag_url": "https://flagcdn.com/w320/do.png", "continent": "North America"},
    {"name": "Ecuador", "flag_url": "https://flagcdn.com/w320/ec.png", "continent": "South America"},
    {"name": "Egypt", "flag_url": "https://flagcdn.com/w320/eg.png", "continent": "Africa"},
    {"name": "El Salvador", "flag_url": "https://flagcdn.com/w320/sv.png", "continent": "North America"},
    {"name": "Equatorial Guinea", "flag_url": "https://flagcdn.com/w320/gq.png", "continent": "Africa"},
    {"name": "Eritrea", "flag_url": "https://flagcdn.com/w320/er.png", "continent": "Africa"},
    {"name": "Estonia", "flag_url": "https://flagcdn.com/w320/ee.png", "continent": "Europe"},
    {"name": "Eswatini", "flag_url": "https://flagcdn.com/w320/sz.png", "continent": "Africa"},
    {"name": "Ethiopia", "flag_url": "https://flagcdn.com/w320/et.png", "continent": "Africa"},
    {"name": "Fiji", "flag_url": "https://flagcdn.com/w320/fj.png", "continent": "Oceania"},
    {"name": "Finland", "flag_url": "https://flagcdn.com/w320/fi.png", "continent": "Europe"},
    {"name": "France", "flag_url": "https://flagcdn.com/w320/fr.png", "continent": "Europe"},
    {"name": "Gabon", "flag_url": "https://flagcdn.com/w320/ga.png", "continent": "Africa"},
    {"name": "Gambia", "flag_url": "https://flagcdn.com/w320/gm.png", "continent": "Africa"},
    {"name": "Georgia", "flag_url": "https://flagcdn.com/w320/ge.png", "continent": "Asia"},
    {"name": "Ghana", "flag_url": "https://flagcdn.com/w320/gh.png", "continent": "Africa"},
    {"name": "Greece", "flag_url": "https://flagcdn.com/w320/gr.png", "continent": "Europe"},
    {"name": "Grenada", "flag_url": "https://flagcdn.com/w320/gd.png", "continent": "North America"},
    {"name": "Guatemala", "flag_url": "https://flagcdn.com/w320/gt.png", "continent": "North America"},
    {"name": "Guinea", "flag_url": "https://flagcdn.com/w320/gn.png", "continent": "Africa"},
    {"name": "Guinea-Bissau", "flag_url": "https://flagcdn.com/w320/gw.png", "continent": "Africa"},
    {"name": "Guyana", "flag_url": "https://flagcdn.com/w320/gy.png", "continent": "South America"},
    {"name": "Haiti", "flag_url": "https://flagcdn.com/w320/ht.png", "continent": "North America"},
    {"name": "Honduras", "flag_url": "https://flagcdn.com/w320/hn.png", "continent": "North America"},
    {"name": "Hungary", "flag_url": "https://flagcdn.com/w320/hu.png", "continent": "Europe"},
    {"name": "Iceland", "flag_url": "https://flagcdn.com/w320/is.png", "continent": "Europe"},
    {"name": "India", "flag_url": "https://flagcdn.com/w320/in.png", "continent": "Asia"},
    {"name": "Indonesia", "flag_url": "https://flagcdn.com/w320/id.png", "continent": "Asia"},
    {"name": "Iran", "flag_url": "https://flagcdn.com/w320/ir.png", "continent": "Asia"},
    {"name": "Iraq", "flag_url": "https://flagcdn.com/w320/iq.png", "continent": "Asia"},
    {"name": "Ireland", "flag_url": "https://flagcdn.com/w320/ie.png", "continent": "Europe"},
    {"name": "Israel", "flag_url": "https://flagcdn.com/w320/il.png", "continent": "Asia"},
    {"name": "Italy", "flag_url": "https://flagcdn.com/w320/it.png", "continent": "Europe"},
    {"name": "Ivory Coast", "flag_url": "https://flagcdn.com/w320/ci.png", "continent": "Africa"},
    {"name": "Jamaica", "flag_url": "https://flagcdn.com/w320/jm.png", "continent": "North America"},
    {"name": "Japan", "flag_url": "https://flagcdn.com/w320/jp.png", "continent": "Asia"},
    {"name": "Jordan", "flag_url": "https://flagcdn.com/w320/jo.png", "continent": "Asia"},
    {"name": "Kazakhstan", "flag_url": "https://flagcdn.com/w320/kz.png", "continent": "Asia"},
    {"name": "Kenya", "flag_url": "https://flagcdn.com/w320/ke.png", "continent": "Africa"},
    {"name": "Kiribati", "flag_url": "https://flagcdn.com/w320/ki.png", "continent": "Oceania"},
    {"name": "Kuwait", "flag_url": "https://flagcdn.com/w320/kw.png", "continent": "Asia"},
    {"name": "Kyrgyzstan", "flag_url": "https://flagcdn.com/w320/kg.png", "continent": "Asia"},
    {"name": "Laos", "flag_url": "https://flagcdn.com/w320/la.png", "continent": "Asia"},
    {"name": "Latvia", "flag_url": "https://flagcdn.com/w320/lv.png", "continent": "Europe"},
    {"name": "Lebanon", "flag_url": "https://flagcdn.com/w320/lb.png", "continent": "Asia"},
    {"name": "Lesotho", "flag_url": "https://flagcdn.com/w320/ls.png", "continent": "Africa"},
    {"name": "Liberia", "flag_url": "https://flagcdn.com/w320/lr.png", "continent": "Africa"},
    {"name": "Libya", "flag_url": "https://flagcdn.com/w320/ly.png", "continent": "Africa"},
    {"name": "Liechtenstein", "flag_url": "https://flagcdn.com/w320/li.png", "continent": "Europe"},
    {"name": "Lithuania", "flag_url": "https://flagcdn.com/w320/lt.png", "continent": "Europe"},
    {"name": "Luxembourg", "flag_url": "https://flagcdn.com/w320/lu.png", "continent": "Europe"},
    {"name": "Madagascar", "flag_url": "https://flagcdn.com/w320/mg.png", "continent": "Africa"},
    {"name": "Malawi", "flag_url": "https://flagcdn.com/w320/mw.png", "continent": "Africa"},
    {"name": "Malaysia", "flag_url": "https://flagcdn.com/w320/my.png", "continent": "Asia"},
    {"name": "Maldives", "flag_url": "https://flagcdn.com/w320/mv.png", "continent": "Asia"},
    {"name": "Mali", "flag_url": "https://flagcdn.com/w320/ml.png", "continent": "Africa"},
    {"name": "Malta", "flag_url": "https://flagcdn.com/w320/mt.png", "continent": "Europe"},
    {"name": "Marshall Islands", "flag_url": "https://flagcdn.com/w320/mh.png", "continent": "Oceania"},
    {"name": "Mauritania", "flag_url": "https://flagcdn.com/w320/mr.png", "continent": "Africa"},
    {"name": "Mauritius", "flag_url": "https://flagcdn.com/w320/mu.png", "continent": "Africa"},
    {"name": "Mexico", "flag_url": "https://flagcdn.com/w320/mx.png", "continent": "North America"},
    {"name": "Micronesia", "flag_url": "https://flagcdn.com/w320/fm.png", "continent": "Oceania"},
    {"name": "Moldova", "flag_url": "https://flagcdn.com/w320/md.png", "continent": "Europe"},
    {"name": "Monaco", "flag_url": "https://flagcdn.com/w320/mc.png", "continent": "Europe"},
    {"name": "Mongolia", "flag_url": "https://flagcdn.com/w320/mn.png", "continent": "Asia"},
    {"name": "Montenegro", "flag_url": "https://flagcdn.com/w320/me.png", "continent": "Europe"},
    {"name": "Morocco", "flag_url": "https://flagcdn.com/w320/ma.png", "continent": "Africa"},
    {"name": "Mozambique", "flag_url": "https://flagcdn.com/w320/mz.png", "continent": "Africa"},
    {"name": "Myanmar", "flag_url": "https://flagcdn.com/w320/mm.png", "continent": "Asia"},
    {"name": "Namibia", "flag_url": "https://flagcdn.com/w320/na.png", "continent": "Africa"},
    {"name": "Nauru", "flag_url": "https://flagcdn.com/w320/nr.png", "continent": "Oceania"},
    {"name": "Nepal", "flag_url": "https://flagcdn.com/w320/np.png", "continent": "Asia"},
    {"name": "Netherlands", "flag_url": "https://flagcdn.com/w320/nl.png", "continent": "Europe"},
    {"name": "New Zealand", "flag_url": "https://flagcdn.com/w320/nz.png", "continent": "Oceania"},
    {"name": "Nicaragua", "flag_url": "https://flagcdn.com/w320/ni.png", "continent": "North America"},
    {"name": "Niger", "flag_url": "https://flagcdn.com/w320/ne.png", "continent": "Africa"},
    {"name": "Nigeria", "flag_url": "https://flagcdn.com/w320/ng.png", "continent": "Africa"},
    {"name": "North Korea", "flag_url": "https://flagcdn.com/w320/kp.png", "continent": "Asia"},
    {"name": "North Macedonia", "flag_url": "https://flagcdn.com/w320/mk.png", "continent": "Europe"},
    {"name": "Norway", "flag_url": "https://flagcdn.com/w320/no.png", "continent": "Europe"},
    {"name": "Oman", "flag_url": "https://flagcdn.com/w320/om.png", "continent": "Asia"},
    {"name": "Pakistan", "flag_url": "https://flagcdn.com/w320/pk.png", "continent": "Asia"},
    {"name": "Palau", "flag_url": "https://flagcdn.com/w320/pw.png", "continent": "Oceania"},
    {"name": "Palestine", "flag_url": "https://flagcdn.com/w320/ps.png", "continent": "Asia"},
    {"name": "Panama", "flag_url": "https://flagcdn.com/w320/pa.png", "continent": "North America"},
    {"name": "Papua New Guinea", "flag_url": "https://flagcdn.com/w320/pg.png", "continent": "Oceania"},
    {"name": "Paraguay", "flag_url": "https://flagcdn.com/w320/py.png", "continent": "South America"},
    {"name": "Peru", "flag_url": "https://flagcdn.com/w320/pe.png", "continent": "South America"},
    {"name": "Philippines", "flag_url": "https://flagcdn.com/w320/ph.png", "continent": "Asia"},
    {"name": "Poland", "flag_url": "https://flagcdn.com/w320/pl.png", "continent": "Europe"},
    {"name": "Portugal", "flag_url": "https://flagcdn.com/w320/pt.png", "continent": "Europe"},
    {"name": "Qatar", "flag_url": "https://flagcdn.com/w320/qa.png", "continent": "Asia"},
    {"name": "Romania", "flag_url": "https://flagcdn.com/w320/ro.png", "continent": "Europe"},
    {"name": "Russia", "flag_url": "https://flagcdn.com/w320/ru.png", "continent": "Europe"},
    {"name": "Rwanda", "flag_url": "https://flagcdn.com/w320/rw.png", "continent": "Africa"},
    {"name": "Saint Kitts and Nevis", "flag_url": "https://flagcdn.com/w320/kn.png", "continent": "North America"},
    {"name": "Saint Lucia", "flag_url": "https://flagcdn.com/w320/lc.png", "continent": "North America"},
    {"name": "Saint Vincent and the Grenadines", "flag_url": "https://flagcdn.com/w320/vc.png", "continent": "North America"},
    {"name": "Samoa", "flag_url": "https://flagcdn.com/w320/ws.png", "continent": "Oceania"},
    {"name": "San Marino", "flag_url": "https://flagcdn.com/w320/sm.png", "continent": "Europe"},
    {"name": "Sao Tome and Principe", "flag_url": "https://flagcdn.com/w320/st.png", "continent": "Africa"},
    {"name": "Saudi Arabia", "flag_url": "https://flagcdn.com/w320/sa.png", "continent": "Asia"},
    {"name": "Senegal", "flag_url": "https://flagcdn.com/w320/sn.png", "continent": "Africa"},
    {"name": "Serbia", "flag_url": "https://flagcdn.com/w320/rs.png", "continent": "Europe"},
    {"name": "Seychelles", "flag_url": "https://flagcdn.com/w320/sc.png", "continent": "Africa"},
    {"name": "Sierra Leone", "flag_url": "https://flagcdn.com/w320/sl.png", "continent": "Africa"},
    {"name": "Singapore", "flag_url": "https://flagcdn.com/w320/sg.png", "continent": "Asia"},
    {"name": "Slovakia", "flag_url": "https://flagcdn.com/w320/sk.png", "continent": "Europe"},
    {"name": "Slovenia", "flag_url": "https://flagcdn.com/w320/si.png", "continent": "Europe"},
    {"name": "Solomon Islands", "flag_url": "https://flagcdn.com/w320/sb.png", "continent": "Oceania"},
    {"name": "Somalia", "flag_url": "https://flagcdn.com/w320/so.png", "continent": "Africa"},
    {"name": "South Africa", "flag_url": "https://flagcdn.com/w320/za.png", "continent": "Africa"},
    {"name": "South Sudan", "flag_url": "https://flagcdn.com/w320/ss.png", "continent": "Africa"},
    {"name": "Spain", "flag_url": "https://flagcdn.com/w320/es.png", "continent": "Europe"},
    {"name": "Sri Lanka", "flag_url": "https://flagcdn.com/w320/lk.png", "continent": "Asia"},
    {"name": "Sudan", "flag_url": "https://flagcdn.com/w320/sd.png", "continent": "Africa"},
    {"name": "Suriname", "flag_url": "https://flagcdn.com/w320/sr.png", "continent": "South America"},
    {"name": "Sweden", "flag_url": "https://flagcdn.com/w320/se.png", "continent": "Europe"},
    {"name": "Switzerland", "flag_url": "https://flagcdn.com/w320/ch.png", "continent": "Europe"},
    {"name": "Syria", "flag_url": "https://flagcdn.com/w320/sy.png", "continent": "Asia"},
    {"name": "Tajikistan", "flag_url": "https://flagcdn.com/w320/tj.png", "continent": "Asia"},
    {"name": "Tanzania", "flag_url": "https://flagcdn.com/w320/tz.png", "continent": "Africa"},
    {"name": "Thailand", "flag_url": "https://flagcdn.com/w320/th.png", "continent": "Asia"},
    {"name": "Timor-Leste", "flag_url": "https://flagcdn.com/w320/tl.png", "continent": "Asia"},
    {"name": "Togo", "flag_url": "https://flagcdn.com/w320/tg.png", "continent": "Africa"},
    {"name": "Tonga", "flag_url": "https://flagcdn.com/w320/to.png", "continent": "Oceania"},
    {"name": "Trinidad and Tobago", "flag_url": "https://flagcdn.com/w320/tt.png", "continent": "North America"},
    {"name": "Tunisia", "flag_url": "https://flagcdn.com/w320/tn.png", "continent": "Africa"},
    {"name": "Turkey", "flag_url": "https://flagcdn.com/w320/tr.png", "continent": "Asia"},
    {"name": "Turkmenistan", "flag_url": "https://flagcdn.com/w320/tm.png", "continent": "Asia"},
    {"name": "Tuvalu", "flag_url": "https://flagcdn.com/w320/tv.png", "continent": "Oceania"},
    {"name": "Uganda", "flag_url": "https://flagcdn.com/w320/ug.png", "continent": "Africa"},
    {"name": "Ukraine", "flag_url": "https://flagcdn.com/w320/ua.png", "continent": "Europe"},
    {"name": "United Arab Emirates", "flag_url": "https://flagcdn.com/w320/ae.png", "continent": "Asia"},
    {"name": "United Kingdom", "flag_url": "https://flagcdn.com/w320/gb.png", "continent": "Europe"},
    {"name": "United States", "flag_url": "https://flagcdn.com/w320/us.png", "continent": "North America"},
    {"name": "Uruguay", "flag_url": "https://flagcdn.com/w320/uy.png", "continent": "South America"},
    {"name": "Uzbekistan", "flag_url": "https://flagcdn.com/w320/uz.png", "continent": "Asia"},
    {"name": "Vanuatu", "flag_url": "https://flagcdn.com/w320/vu.png", "continent": "Oceania"},
    {"name": "Vatican City", "flag_url": "https://flagcdn.com/w320/va.png", "continent": "Europe"},
    {"name": "Venezuela", "flag_url": "https://flagcdn.com/w320/ve.png", "continent": "South America"},
    {"name": "Vietnam", "flag_url": "https://flagcdn.com/w320/vn.png", "continent": "Asia"},
    {"name": "Yemen", "flag_url": "https://flagcdn.com/w320/ye.png", "continent": "Asia"},
    {"name": "Zambia", "flag_url": "https://flagcdn.com/w320/zm.png", "continent": "Africa"},
    {"name": "Zimbabwe", "flag_url": "https://flagcdn.com/w320/zw.png", "continent": "Africa"}
]